import './global.css';
import '@pigment-css/react/styles.css';
import '@arctic-kit/snow/style.css';

import { inter } from '@/fonts';

export const metadata = {
  title: 'Welcome to iceberg',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="theme-light">
      <body className={`${inter.className} antialiased`}>{children}</body>
    </html>
  );
}
